export const TOGGLE_MAIN_MENU = 'TOGGLE_MAIN_MENU';
export const GET_PROGRESS = 'GET_PROGRESS';
export const GET_PROGRESS_PENDING ='GET_PROGRESS_PENDING';
export const GET_PROGRESS_FULFILLED='GET_PROGRESS_FULFILLED';
export const GET_PROGRESS_REJECTED='GET_PROGRESS_REJECTED';